### ISSUE TITLE
Address GPIO18 conflict between fan shim and bling

### ISSUE THREAD

**Issue by kajames** [FRC2706/blingServer#39]
The GPIO18 pin is used by the bling code as the signal output (GPIO18 is one of the PWM0 outputs) and by the fan shim as the fan control pin. Although the two appear to work ok on merge41 we need to make sure there is no issue on the competition robot. Steps to take:
*1 run bling and fan at the same time (using the stress program to raise the cpu temp high enough to start the fan) and see what impact there is to the fan and/or bling
*2 try re-configuring the bling code to use the other PWM0 GPIO on the PI (test using a modified strandtest.py)

If there is conflict there are, at least, the following ways we can go (there may be more)
*1 no bling (boo!)
*2 different fan solution
*3 bling on another port

**Comment by Ketchperiment** [comment]
SOLVED!
Turns out there's a super easy way to switch the PWM channel that the bling code operates on, 
![image](https://user-images.githubusercontent.com/16737033/72765383-16c22700-3bba-11ea-8350-3c66db91c93b.png)
Set the LED_CHANNEL to 1 to be able to use gpio pins on PWM1
I decided to attach the bling wire to GPIO 13, but 19 could be used if desired.

Along with this fix, I had to change which pin the status led uses on boot, the green one that indicates when a user is able to log in/ssh into the pi - I set it to pin 16 because it was nice and close

The python file to do this can be found in /usr/local/bin/blink-service-led.py
